spring:
  profiles:
    active: local
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        PhysicalNamingStrategyStandardImpl: physical
server:
  port: 5000
