spring:
  flyway:
    schemas: ""
    url: ""
    username: ""
    password: ""
    encoding: UTF-8
  datasource:
    url: ""
    username: ""
    password: ""
  batch:
    initialize-schema: always
    job:
      names: none

sync:
  network: CYPRESS
  forward: true
  back: false
  scope: REGISTERED_EVENTS

logging:
  level:
    org:
      springframework:
        web: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

